### ISSUE TITLE
SentryLogger usage

### ISSUE THREAD

**Issue by tom71** [wizpanda/kernel#13]
Hello,
I want use the SentryLogger in my grails app. I can integrate the plugin. But I have problems to configure the servername and dsn. How can I do this? When is the init() called from SentryLogger?

Thank you

**Comment by sagrawal31** [comment]
Yes, you can use `SentryLogger` in your app. We have been using this on our production app for Millions of users. For `servername`, you can pass null. For `dsn`, signup on https://sentry.io/ and create a Java/Spring app and get the DSN.

**Comment by tom71** [comment]
Hi, 
thank you. The DSN I already have. But were I can configure the SentryLogger? Simply call the init method ? Or in my application.yml file?

**Comment by sagrawal31** [comment]
Sorry, my bad. I used to call `SentryLogger.init()` in `Bootstrap.groovy` as that I find the best place to kick in the Sentry. Although, it won't capture anything before bootstrap.

**Comment by tom71** [comment]
OK, that sounds good and works. Thank you
